// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: address.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO
    public.address (street, landmark, city, pincode, hospital_id)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, street, landmark, city, pincode, hospital_id
`

type CreateAddressParams struct {
	Street     string
	Landmark   sql.NullString
	City       string
	Pincode    string
	HospitalID int32
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, createAddress,
		arg.Street,
		arg.Landmark,
		arg.City,
		arg.Pincode,
		arg.HospitalID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Street,
		&i.Landmark,
		&i.City,
		&i.Pincode,
		&i.HospitalID,
	)
	return i, err
}
