// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: amenity.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createAmenity = `-- name: CreateAmenity :many
INSERT INTO
    public.amenity (name)
SELECT
    unnest($1::INT[]) AS name
RETURNING
    id, name
`

func (q *Queries) CreateAmenity(ctx context.Context, names []int32) ([]Amenity, error) {
	rows, err := q.db.QueryContext(ctx, createAmenity, pq.Array(names))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amenity
	for rows.Next() {
		var i Amenity
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAmenities = `-- name: GetAllAmenities :many
SELECT
    id, name
FROM
    public.amenity
`

func (q *Queries) GetAllAmenities(ctx context.Context) ([]Amenity, error) {
	rows, err := q.db.QueryContext(ctx, getAllAmenities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amenity
	for rows.Next() {
		var i Amenity
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
