// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: hospital_doctors.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createHospitalDoctors = `-- name: CreateHospitalDoctors :many
INSERT INTO
    public.hospital_doctors (doctor_id, hospital_id)
SELECT
    unnest($1::INT[]) AS doctor_id,
    unnest($2::INT[]) AS hospital_id
RETURNING
    id, doctor_id, hospital_id
`

type CreateHospitalDoctorsParams struct {
	DoctorIds   []int32
	HospitalIds []int32
}

func (q *Queries) CreateHospitalDoctors(ctx context.Context, arg CreateHospitalDoctorsParams) ([]HospitalDoctor, error) {
	rows, err := q.db.QueryContext(ctx, createHospitalDoctors, pq.Array(arg.DoctorIds), pq.Array(arg.HospitalIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HospitalDoctor
	for rows.Next() {
		var i HospitalDoctor
		if err := rows.Scan(&i.ID, &i.DoctorID, &i.HospitalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
