// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: hospital_image.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createHospitalImageWithHospitalID = `-- name: CreateHospitalImageWithHospitalID :many
INSERT INTO
    public.hospital_image (src, hospital_id)
SELECT
    unnest($1::VARCHAR(255)[]) AS src,
    unnest($2::INT[]) AS hospital_id
RETURNING
    id, src, hospital_id
`

type CreateHospitalImageWithHospitalIDParams struct {
	Srcs        []string
	HospitalIds []int32
}

func (q *Queries) CreateHospitalImageWithHospitalID(ctx context.Context, arg CreateHospitalImageWithHospitalIDParams) ([]HospitalImage, error) {
	rows, err := q.db.QueryContext(ctx, createHospitalImageWithHospitalID, pq.Array(arg.Srcs), pq.Array(arg.HospitalIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HospitalImage
	for rows.Next() {
		var i HospitalImage
		if err := rows.Scan(&i.ID, &i.Src, &i.HospitalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
