// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: hospital_insurance_partners.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createHospitalInsurancePartners = `-- name: CreateHospitalInsurancePartners :many
INSERT INTO
    public.hospital_insurance_partners (insurance_partner_id, hospital_id)
SELECT
    unnest($1::INT[]) AS insurance_partner_id,
    unnest($2::INT[]) AS hospital_id
RETURNING
    id, insurance_partner_id, hospital_id
`

type CreateHospitalInsurancePartnersParams struct {
	InsurancePartnerIds []int32
	HospitalIds         []int32
}

func (q *Queries) CreateHospitalInsurancePartners(ctx context.Context, arg CreateHospitalInsurancePartnersParams) ([]HospitalInsurancePartner, error) {
	rows, err := q.db.QueryContext(ctx, createHospitalInsurancePartners, pq.Array(arg.InsurancePartnerIds), pq.Array(arg.HospitalIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HospitalInsurancePartner
	for rows.Next() {
		var i HospitalInsurancePartner
		if err := rows.Scan(&i.ID, &i.InsurancePartnerID, &i.HospitalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
