// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: hospital.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteHospitalByID = `-- name: DeleteHospitalByID :exec
DELETE FROM public.hospital
WHERE
    id = $1
`

func (q *Queries) DeleteHospitalByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteHospitalByID, id)
	return err
}

const getHospitalByID = `-- name: GetHospitalByID :one
INSERT INTO
    public.hospital (name, lat, long, cost, accreditation, wait_time, capacity, site_url, contact_number, ratings)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id, name, lat, long, cost, accreditation, wait_time, capacity, site_url, contact_number, ratings
`

type GetHospitalByIDParams struct {
	Name          string
	Lat           string
	Long          string
	Cost          int32
	Accreditation sql.NullString
	WaitTime      int32
	Capacity      int32
	SiteUrl       sql.NullString
	ContactNumber string
	Ratings       string
}

// SELECT
//
//	h.id AS hospital_id,
//	h.name AS hospital_name,
//	h.lat,
//	h.long,
//	h.cost,
//	h.accreditation,
//	h.wait_time,
//	h.capacity,
//	h.site_url,
//	h.contact_number,
//	h.ratings,
//	ARRAY_AGG(JSON_BUILD_OBJECT('id', hi.id, 'src', hi.src)) AS images,
//	JSON_BUILD_OBJECT('id', a.id, 'street', a.street, 'landmark', a.landmark, 'city', a.city, 'pincode', a.pincode) AS address
//
// FROM
//
//	hospital h
//	LEFT JOIN hospital_image hi ON h.id = hi.hospital_id
//	LEFT JOIN address a ON h.id = a.hospital_id
//
// WHERE
//
//	h.id = $1
//
// GROUP BY
//
//	h.id,
//	a.id;
func (q *Queries) GetHospitalByID(ctx context.Context, arg GetHospitalByIDParams) (Hospital, error) {
	row := q.db.QueryRowContext(ctx, getHospitalByID,
		arg.Name,
		arg.Lat,
		arg.Long,
		arg.Cost,
		arg.Accreditation,
		arg.WaitTime,
		arg.Capacity,
		arg.SiteUrl,
		arg.ContactNumber,
		arg.Ratings,
	)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lat,
		&i.Long,
		&i.Cost,
		&i.Accreditation,
		&i.WaitTime,
		&i.Capacity,
		&i.SiteUrl,
		&i.ContactNumber,
		&i.Ratings,
	)
	return i, err
}
