// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: hospital_departments.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createHospitalDepartments = `-- name: CreateHospitalDepartments :many
INSERT INTO
    public.hospital_departments (department_id, hospital_id)
SELECT
    unnest($1::INT[]) AS department_id,
    unnest($2::INT[]) AS hospital_id
RETURNING
    id, department_id, hospital_id
`

type CreateHospitalDepartmentsParams struct {
	DepartmentIds []int32
	HospitalIds   []int32
}

func (q *Queries) CreateHospitalDepartments(ctx context.Context, arg CreateHospitalDepartmentsParams) ([]HospitalDepartment, error) {
	rows, err := q.db.QueryContext(ctx, createHospitalDepartments, pq.Array(arg.DepartmentIds), pq.Array(arg.HospitalIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HospitalDepartment
	for rows.Next() {
		var i HospitalDepartment
		if err := rows.Scan(&i.ID, &i.DepartmentID, &i.HospitalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
