// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Address struct {
	ID         int32
	Street     string
	Landmark   sql.NullString
	City       string
	Pincode    string
	HospitalID int32
}

type Amenity struct {
	ID   int32
	Name string
}

type Department struct {
	ID   int32
	Name string
}

type Doctor struct {
	ID               int32
	Name             string
	Background       string
	EducationDetails string
	Experience       int16
	Fees             int32
	DepartmentID     int32
}

type Hospital struct {
	ID            int32
	Name          string
	Lat           string
	Long          string
	Cost          int32
	Accreditation sql.NullString
	WaitTime      int32
	Capacity      int32
	SiteUrl       sql.NullString
	ContactNumber string
	Ratings       string
}

type HospitalAmenity struct {
	ID         int32
	AmenityID  int32
	HospitalID int32
}

type HospitalDepartment struct {
	ID           int32
	DepartmentID int32
	HospitalID   int32
}

type HospitalDoctor struct {
	ID         int32
	DoctorID   int32
	HospitalID int32
}

type HospitalImage struct {
	ID         int32
	Src        string
	HospitalID int32
}

type HospitalInsurancePartner struct {
	ID                 int32
	InsurancePartnerID int32
	HospitalID         int32
}

type InsurancePartner struct {
	ID   int32
	Name string
}
